/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doan1;

import java.sql.Connection;
import java.sql.DriverManager;
import static java.sql.DriverManager.getConnection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class Thêm_Nhân_Viên extends javax.swing.JFrame {

    /**
     * Creates new form QuanLiNhanVien
     */
    public Thêm_Nhân_Viên() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Age = new javax.swing.JLabel();
        jLabel_Name = new javax.swing.JLabel();
        jLabel_Address = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel_PhoneNum = new javax.swing.JLabel();
        jTextField_HOTEN = new javax.swing.JTextField();
        jTextField_AGE = new javax.swing.JTextField();
        jTextField_Address = new javax.swing.JTextField();
        jTextField_PhoneNum = new javax.swing.JTextField();
        jLabel_Tittle = new javax.swing.JLabel();
        jButton_ADD = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField_MãVN = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Age.setText("Tuổi");
        getContentPane().add(jLabel_Age, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 190, 30, 20));

        jLabel_Name.setText("Họ và Tên");
        getContentPane().add(jLabel_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        jLabel_Address.setText("Địa chỉ");
        getContentPane().add(jLabel_Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 249, 58, 26));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 242, -1, -1));

        jLabel_PhoneNum.setText("Số điện thoại");
        getContentPane().add(jLabel_PhoneNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 311, -1, -1));

        jTextField_HOTEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_HOTENActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_HOTEN, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 212, -1));

        jTextField_AGE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_AGEActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_AGE, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 212, -1));
        getContentPane().add(jTextField_Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 212, -1));

        jTextField_PhoneNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_PhoneNumActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_PhoneNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 308, 212, -1));

        jLabel_Tittle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Tittle.setText("BỔ SUNG NHÂN VIÊN");
        getContentPane().add(jLabel_Tittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 180, 65));

        jButton_ADD.setText("Add");
        jButton_ADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ADDActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_ADD, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 362, 180, 37));

        jLabel1.setText("Mã NV");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));
        getContentPane().add(jTextField_MãVN, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 210, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_AGEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_AGEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_AGEActionPerformed

    private void jTextField_PhoneNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PhoneNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PhoneNumActionPerformed

    private void jButton_ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ADDActionPerformed
        // TODO add your handling code here:
        String insert_sql = "INSERT INTO theater.staff VALUES (?, ?, ?, ?, ?);";
        Connection conn = null;
        PreparedStatement statement = null;
        try {
            conn = getConnection("jdbc:mysql://localhost:3306/Theater?", "root", "ducanh113");
        } catch (SQLException ex) {
            Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            statement = conn.prepareCall(insert_sql);

        } catch (SQLException ex) {
            Logger.getLogger(Thêm_Nhân_Viên.class.getName()).log(Level.SEVERE, null, ex);
        }

        String add_MaNV = jTextField_MãVN.getText();
        String add_Name = jTextField_HOTEN.getText();
        String add_Age = jTextField_AGE.getText();
        String add_PhoneNum = jTextField_PhoneNum.getText();
        String add_Address = jTextField_Address.getText();

        try {           
            statement.setInt(1, Integer.parseInt(add_MaNV));
            statement.setString(2, add_Name);
            statement.setInt(3, Integer.parseInt(add_Age));
            statement.setString(4, add_PhoneNum);
            statement.setString(5, add_Address);
            statement.execute();
            JOptionPane.showMessageDialog(rootPane, "SUCCESS");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "FAILED. PLEASE TRY AGAIN");
            jTextField_MãVN.setText("");
            jTextField_HOTEN.setText("");
            jTextField_AGE.setText("");
            jTextField_Address.setText("");
            jTextField_PhoneNum.setText("");
        }


    }//GEN-LAST:event_jButton_ADDActionPerformed

    private void jTextField_HOTENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_HOTENActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_HOTENActionPerformed
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Xóa_Nhân_Viên.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Xóa_Nhân_Viên.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Xóa_Nhân_Viên.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Xóa_Nhân_Viên.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Thêm_Nhân_Viên().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_ADD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_Address;
    private javax.swing.JLabel jLabel_Age;
    private javax.swing.JLabel jLabel_Name;
    private javax.swing.JLabel jLabel_PhoneNum;
    private javax.swing.JLabel jLabel_Tittle;
    private javax.swing.JTextField jTextField_AGE;
    private javax.swing.JTextField jTextField_Address;
    private javax.swing.JTextField jTextField_HOTEN;
    private javax.swing.JTextField jTextField_MãVN;
    private javax.swing.JTextField jTextField_PhoneNum;
    // End of variables declaration//GEN-END:variables
}
